title: 'Jeremy Cherfas'
default_lang: en
author:
  name: 'Jeremy Cherfas'
  email: grav@jcherfas.fastmail.fm
taxonomies:
  - category
  - tag
metadata:
  description: 'A personal website that tries to be IndieWeb'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
